header:
  license:
    content: "SPDX-License-Identifier: GPL-3.0-or-later"
  paths:
    - '**/*.rs'
  paths-ignore:
    - '**/*.md'
    - '**/.git/**'
  comment: on-failure
  license-location-threshold: 10
